[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.146.0"  # 升级到PaperMod要求的最低版本
  HUGO_EXTENDED = "true"    # 启用扩展版本

[context.production.environment]
  HUGO_ENV = "production"
    